language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

sudo: false
dist: trusty

# Noticate via slack
notifications:
  slack: projetodoesangue:n3fh7tZf7ZtGAiqzQPlIypiI

install: npm install -g codecov

# Test if app works as expected
script:
 - npm test
# - npm run unit
 - codecov

before_deploy:
  - npm run build
deploy:
  provider: surge
  project: ./dist/
  domain: demo.doesangue.me
# The branch we will use to deploy
  on: development
  skip_cleanup: true
